export const COUNTRIES = [
    { code: "KH", name: "Cambodian", flag: "🇰🇭" },
    { code: "US", name: "American", flag: "🇺🇸" },
    { code: "GB", name: "British", flag: "🇬🇧" },
    { code: "AU", name: "Australian", flag: "🇦🇺" },
    { code: "CA", name: "Canadian", flag: "🇨🇦" },
    { code: "FR", name: "French", flag: "🇫🇷" },
    { code: "DE", name: "German", flag: "🇩🇪" },
    { code: "CN", name: "Chinese", flag: "🇨🇳" },
    { code: "JP", name: "Japanese", flag: "🇯🇵" },
    { code: "KR", name: "Korean", flag: "🇰🇷" },
    { code: "VN", name: "Vietnamese", flag: "🇻🇳" },
    { code: "TH", name: "Thai", flag: "🇹🇭" },
    { code: "SG", name: "Singaporean", flag: "🇸🇬" },
    { code: "MY", name: "Malaysian", flag: "🇲🇾" },
    { code: "ID", name: "Indonesian", flag: "🇮🇩" },
    { code: "PH", name: "Filipino", flag: "🇵🇭" },
    { code: "IN", name: "Indian", flag: "🇮🇳" },
    { code: "RU", name: "Russian", flag: "🇷🇺" },
    { code: "UA", name: "Ukrainian", flag: "🇺🇦" },
    { code: "IT", name: "Italian", flag: "🇮🇹" },
    { code: "ES", name: "Spanish", flag: "🇪🇸" },
    { code: "BE", name: "Belgian", flag: "🇧🇪" },
    { code: "NL", name: "Dutch", flag: "🇳🇱" },
    { code: "CH", name: "Swiss", flag: "🇨🇭" },
    { code: "SE", name: "Swedish", flag: "🇸🇪" },
    { code: "NO", name: "Norwegian", flag: "🇳🇴" },
    { code: "DK", name: "Danish", flag: "🇩🇰" },
    { code: "FI", name: "Finnish", flag: "🇫🇮" },
    { code: "IE", name: "Irish", flag: "🇮🇪" },
    { code: "NZ", name: "New Zealander", flag: "🇳🇿" },
    { code: "BR", name: "Brazilian", flag: "🇧🇷" },
    { code: "MX", name: "Mexican", flag: "🇲🇽" },
    { code: "AR", name: "Argentinian", flag: "🇦🇷" },
    { code: "ZA", name: "South African", flag: "🇿🇦" },
    { code: "NG", name: "Nigerian", flag: "🇳🇬" },
    { code: "EG", name: "Egyptian", flag: "🇪🇬" },
    { code: "SA", name: "Saudi Arabian", flag: "🇸🇦" },
    { code: "AE", name: "Emirati", flag: "🇦🇪" },
    { code: "QA", name: "Qatari", flag: "🇶🇦" },
    { code: "OTHER", name: "Other", flag: "🏳️" }
];
